site_name: pyinterview
repo_name: marwanhawari/pyinterview
repo_url: https://github.com/marwanhawari/pyinterview
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: cyan
  logo: pyinterview_icon.png
  plugins:
  - search
  - social
  features:
  - search.suggest
  - search.highlight
nav:
  - Algorithms:
    - Searching: "algorithms/searching.md"
    - Sorting: "algorithms/sorting.md"
  - Data structures: 
    - Graphs: "data_structures/graphs.md"
    - Heaps: "data_structures/heaps.md"
    - Linked lists: "data_structures/linked_lists.md"
    - Trees: "data_structures/trees.md"
    - Tries: "data_structures/tries.md"

