site_name: pyinterview
repo_name: marwanhawari/pyinterview
repo_url: https://github.com/marwanhawari/pyinterview
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: cyan
  logo: pyinterview_icon.png
  plugins:
  - search
  - social
  features:
  - search.suggest
  - search.highlight
nav:
  - Graphs: "graphs.md"
  - Heaps: "heaps.md"
  - Linked lists: "linked_lists.md"
  - Searching algorithms: "searching.md"
  - Sorting algorithms: "sorting.md"
  - Trees: "trees.md"
  - Tries: "tries.md"

