site_name: pyinterview
repo_name: marwanhawari/pyinterview
repo_url: https://github.com/marwanhawari/pyinterview
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: cyan
  logo: pyinterview_icon.png
  plugins:
  - search
  - social
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("pyinterview")
          rendering:
            show_source: true
      watch:
        - pyinterview
  features:
  - search.suggest
  - search.highlight
markdown_extensions:
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Algorithms:
    - Searching: algorithms/searching.md
    - Sorting: algorithms/sorting.md
  - Data structures: 
    - Graphs: data_structures/graphs.md
    - Heaps: data_structures/heaps.md
    - Linked lists: data_structures/linked_lists.md
    - Trees: data_structures/trees.md
    - Tries: data_structures/tries.md

