name: docs
on:
  push:
    branches: 
      - main
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install --upgrade pip
      - run: pip install mkdocs-material mkdocstrings
      - run: mkdocs gh-deploy --force
